[build]
  publish = "."
  functions = "netlify/functions"

# Public API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/public/:splat"
  status = 200

# Auth API routes
[[redirects]]
  from = "/api-auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

# Mutations (writes)
[[redirects]]
  from = "/api-mutate/*"
  to = "/.netlify/functions/mutate/:splat"
  status = 200

# Admin routes
[[redirects]]
  from = "/api-admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200

# Pro score updater
[[redirects]]
  from = "/api-proscore"
  to = "/.netlify/functions/proscore"
  status = 200
